---
- name: install uacme package
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - uacme
  tags: [packages]

- name: create a group for uacme
  become: yes
  group:
    state: present
    name: acme
  tags: [prepare]

- name: create a user for uacme
  become: yes
  user:
    name: acme
    home: "/var/lib/acme"
    system: "yes"
    shell: "/bin/nologin"
    state: present
    groups: "acme,www-data"
  tags: [prepare]

- name: create uacme dir on /etc/ssl
  file:
    path: /etc/ssl/uacme
    state: directory
    group: acme
    owner: acme
    mode: "g+rX"
  tags: [prepare]

- name: create private uacme dir on /etc/ssl
  file:
    path: /etc/ssl/uacme/private
    state: directory
    group: acme
    owner: acme
    mode: "g+rX"
  tags: [prepare]

- name: create acme challenges dirs on /var/www
  become: yes
  file:
    path: /var/www/.well-known/acme-challenge
    state: directory
    group: acme
    owner: acme
  tags: [prepare]

- name: create acme log
  become: yes
  loop: "{{ vhosts }}"
  file:
    path: "/var/log/acme-{{item}}.log"
    state: touch
    group: acme
    owner: acme
  tags: [prepare, acme-install]

- name: copy acme-update-certs script
  become: yes
  template:
    src: acme-update-certs.j2
    dest: /usr/local/bin/acme-update-certs
    mode: "+x"
  tags:
    - nginx
    - acme-install

- name: renew certs
  loop: "{{ vhosts }}"
  ansible.builtin.command: "/usr/local/bin/acme-update-certs {{ item }}"
  notify: nginx reload
  tags:
    - renew-certs
