---
- name: add bitwarden group
  become: yes
  group:
    name: bitwarden
    state: present

- name: add bitwarden user
  become: yes
  user:
    name: bitwarden
    home: "/var/lib/bitwarden"
    groups: 'bitwarden,docker'
    state: present
    system: "yes"

- name: install vaultwarden systemd service unit
  become: yes
  template:
    src: vaultwarden.service.j2
    dest: /etc/systemd/system/vaultwarden.service
  tags: [service]

- name: start and enable vaultwarden service
  become: yes
  systemd:
    name: vaultwarden
    state: started
    enabled: true
    daemon_reload: true
  tags: [service]
