---
- name: set hostname
  hostname: name={{ system_hostname }}
  when: system_hostname is defined
  tags: [common]

- name: set /etc/hostname
  command: echo -n {{ system_hostname }} > /etc/hostname
  when: system_hostname is defined
  tags: [common]

- name: set /etc/timezone
  command: echo -n 'America/Sao_Paulo' > /etc/timezone
  tags: [common]

- name: reconfigure clock
  command: dpkg-reconfigure -f noninteractive tzdata
  tags: [common]

- name: install important sysadmin packages
  apt:
    state: present
    update_cache: yes
    name:
      - doas
      - strace
      - lsof
      - ca-certificates
      - ntp
      - git
      - curl
      - vim
      - htop
      - iotop
      - rsync
      - ncdu
  tags: [common, packages]

- name: install doas.conf
  ansible.builtin.template:
    src: doas.conf.j2
    dest: /etc/doas.conf
    mode: '0644'

- name: disable openssh debian banner
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?DebianBanner"
    line: "DebianBanner no"
  notify: reload ssh
